version: '3.9'

services:
  backend:
    container_name: rental_car_backend
    build: .
    ports:
      - 3001:3001
    depends_on:
      db:
        condition: service_healthy
    environment:
      - PORT=3001
      - DB_USER=root
      - DB_PASS=password
      - DB_HOST=db
      - DB_PORT=3306
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"] # Port for backend
      timeout: 10s
      retries: 5

  db:
    image: mysql:8.0.32
    container_name: rental_car_db
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"] # wait database to start
      timeout: 10s
      retries: 5
